const express = require('express');
const hostrouter = express.Router();
const  rootdir= require('../utils/path_util');
const  homecontroller= require('../controllers/hostcontroller');
hostrouter.get("/add-home",homecontroller.getaddhome);
hostrouter.post("/add-home",homecontroller.postaddhome);
hostrouter.get("/host-home-list",homecontroller.hostgethome);
hostrouter.get("/edit-home/:homeId", homecontroller.getEditHome);
hostrouter.post("/edithome", homecontroller.postEditHome);
hostrouter.post("/delete/:homeId", homecontroller.postDelethome);
exports.hostRouter = hostrouter;